# Generated by Django 4.2.3 on 2023-08-02 08:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
